### PR TITLE
ENH: added Atracsys geometries + 2 config files for SlicerAstmPhantomTest

### PR DESCRIPTION
**Pull request by atracsys-sbt**
As part of the [integration of SlicerAstmPhantomTest](https://github.com/Slicer/ExtensionsIndex/pull/1840#issuecomment-1154824485) into the Slicer extensions index, I added six common geometries from Atracsys and two examples of configuration for the Plus Server to work with the aforementioned Slicer extension.

### CODE REVIEW

**Comment by lassoan** [comment]
@atracsys-sbt Do you want these configuration files included in Plus installation packages?

**Comment by atracsys-sbt** [comment]
> @atracsys-sbt Do you want these configuration files included in Plus installation packages?

Yes, that'd be great !

**Comment by Sunderlandkyl** [comment]
Added to packages here: https://github.com/PlusToolkit/PlusApp/commit/69abd1e03f9cbb0703c246938dcfd88afe24f40f.

**Comment by lassoan** [comment]
Great, thank you Kyle.

**Comment by atracsys-sbt** [comment]
Hi, after installing the latest version of Plus, I realized that the "ASTM phantom test" config file for NDI devices is missing: ConfigFiles/PlusDeviceSet_Server_AstmPhantomTest_NDI_Polaris.xml
@Sunderlandkyl Would it be possible to add it to the Plus installation packages like the other one ?

**Comment by Sunderlandkyl** [comment]
Sure, [done](https://github.com/PlusToolkit/PlusApp/commit/fbfaf94a69b32d05da57b5e2fa2617f1e4fd07bf).

**Comment by atracsys-sbt** [comment]
Thank you, but at the risk of being picky, this configuration file relates to NDI devices, not Atracsys, so I think it would be better to include it under [IF(PLUS_USE_NDI)](https://github.com/PlusToolkit/PlusApp/blob/fbfaf94a69b32d05da57b5e2fa2617f1e4fd07bf/InstallFiles.cmake#L242) instead.

**Comment by Sunderlandkyl** [comment]
Ah you are right. I've moved to the correct location.

**Pull request merged**
