### PR TITLE
Change mha/mhd/nrrd to compound .igs extension

### PR DESCRIPTION
**Pull request by Sunderlandkyl**

### CODE REVIEW

**Comment by lassoan** [comment]
Looks good.

Have you checked the parts where you need to strip file extension (e.g., to get a base name that will have timestamp added to) work correctly? Stripping should first look for the composite extension ".igs.nrrd" if found then remove that; if not found then try ".nrrd", if found then remove that.

Have you paid attention not to add .igs to 3D reconstructed volumes? (it seems so, I'm asking just to double-check)

**Comment by Sunderlandkyl** [comment]
1. I'll double check
2. No, I didn't. I'll go through the files and see if I renamed some by accident.

**Comment by Sunderlandkyl** [comment]
1. I can confirm that  vtksys::SystemTools::GetFilenameWithoutExtension() is used in vtkPlusVirtualCapture to remove the entire compound extension before adding the date.
2. The reconstructed volumes should not be renamed now.

**Comment by lassoan** [comment]
Does vtksys::SystemTools::GetFilenameWithoutExtension() consider everything after the first "." as extension? In general the only relia le way of removing file extensions if you have a list of known extensions.

**Comment by Sunderlandkyl** [comment]
Yes it uses the following code:
```
std::string::size_type dot_pos = name.find('.');
if(dot_pos != std::string::npos)
  {
  return name.substr(0, dot_pos);
  }
```

**Comment by lassoan** [comment]
That unfortunately is not good. It would give incorrect results for names containing dot.

**Pull request merged**
